export const user = state => state.user
export const isOwner = state => state.isOwner
export const isLogin = state => state.isLogin
export const apiURL = state => state.apiURL
export const isCartOpen = state => state.isCartOpen
export const isProfileOpen = state => state.isProfileOpen
export const isOrderOpen = state => state.isOrderOpen
export const isEditCanteenOpen = state => state.isEditCanteenOpen
export const cart = state => state.cart
export const cartCanteen = state => state.cartCanteen
export const editingCanteen = state => state.editingCanteen
export const addingDishTypeId = state => state.addingDishTypeId
export const isAddCanteen = state => state.isAddCanteen
export const isAddDishOpen = state => state.isAddDishOpen
export const canteenID = state => state.canteenID